import FormalConjectures.Problems.Erdos.E61.RootedP4Cubes

/-!
# Explicit crossing-cube template closures

This file formalizes the `H`-specific obstruction for the two explicit rooted
`P4` cube template families constructed in the paper: the private-matching
cube `PM_m` and the Boolean-star cube `BS_m`.

The closure predicates here are the hereditary closures generated by these
checked template families, phrased directly as induced containment in one of
the finite cube graphs.
-/

namespace Erdos61

/-- `H` belongs to the hereditary closure generated by private-matching cubes. -/
def PrivateMatchingCubeClosure {W : Type*} (H : SimpleGraph W) : Prop :=
  ∃ m : ℕ, H.IsIndContained (PMVertex.graph m)

/-- `H` belongs to the hereditary closure generated by Boolean-star cubes. -/
def BooleanStarCubeClosure {W : Type*} (H : SimpleGraph W) : Prop :=
  ∃ m : ℕ, H.IsIndContained (BSVertex.graph m)

/-- If `H` is outside the private-matching cube closure, every `PM_m` is `H`-free. -/
theorem privateMatchingCube_inducedFree_of_not_mem_closure
    {W : Type*} {H : SimpleGraph W}
    (hH : ¬ PrivateMatchingCubeClosure H) (m : ℕ) :
    ¬ H.IsIndContained (PMVertex.graph m) := by
  intro hcopy
  exact hH ⟨m, hcopy⟩

/-- If `H` is outside the Boolean-star cube closure, every `BS_m` is `H`-free. -/
theorem booleanStarCube_inducedFree_of_not_mem_closure
    {W : Type*} {H : SimpleGraph W}
    (hH : ¬ BooleanStarCubeClosure H) (m : ℕ) :
    ¬ H.IsIndContained (BSVertex.graph m) := by
  intro hcopy
  exact hH ⟨m, hcopy⟩

/--
`H`-specific private-matching obstruction: outside the private-matching cube
closure, there are `H`-free purified configurations whose crossing traces
shatter a matching of any prescribed size.
-/
theorem H_specific_privateMatching_cubes
    {W : Type*} {H : SimpleGraph W}
    (hH : ¬ PrivateMatchingCubeClosure H) (m : ℕ) :
    ¬ H.IsIndContained (PMVertex.graph m) ∧
      IsPurifiedRootedP4 (PMVertex.graph m)
        (PMVertex.B₁ m) (PMVertex.B₂ m) (PMVertex.B₃ m) (PMVertex.B₄ m) (PMVertex.Y m) ∧
      (PMVertex.middleEdges m).card = m ∧
      (crossingTraceFamily (PMVertex.graph m)
        (PMVertex.B₁ m) (PMVertex.B₂ m) (PMVertex.B₃ m) (PMVertex.B₄ m)
        (PMVertex.Y m)).Shatters (PMVertex.middleEdges m) := by
  exact ⟨privateMatchingCube_inducedFree_of_not_mem_closure hH m,
    PMVertex.purified m, PMVertex.middleEdges_card m,
    PMVertex.privateMatching_crossingTraceFamily_shatters_matching m⟩

/--
`H`-specific Boolean-star obstruction: outside the Boolean-star cube closure,
there are `H`-free purified configurations whose crossing traces shatter a star
of any prescribed size.
-/
theorem H_specific_booleanStar_cubes
    {W : Type*} {H : SimpleGraph W}
    (hH : ¬ BooleanStarCubeClosure H) (m : ℕ) :
    ¬ H.IsIndContained (BSVertex.graph m) ∧
      IsPurifiedRootedP4 (BSVertex.graph m)
        (BSVertex.B₁ m) (BSVertex.B₂ m) (BSVertex.B₃ m) (BSVertex.B₄ m) (BSVertex.Y m) ∧
      (BSVertex.middleEdges m).card = m ∧
      (crossingTraceFamily (BSVertex.graph m)
        (BSVertex.B₁ m) (BSVertex.B₂ m) (BSVertex.B₃ m) (BSVertex.B₄ m)
        (BSVertex.Y m)).Shatters (BSVertex.middleEdges m) := by
  exact ⟨booleanStarCube_inducedFree_of_not_mem_closure hH m,
    BSVertex.purified m, BSVertex.middleEdges_card m,
    BSVertex.booleanStar_crossingTraceFamily_shatters_star m⟩

/--
Combined form of `thm:H-specific-cubes`, bundling the private-matching and
Boolean-star directions.
-/
theorem H_specific_crossing_cube_obstruction
    {W : Type*} (H : SimpleGraph W) :
    (¬ PrivateMatchingCubeClosure H →
      ∀ m : ℕ,
        ¬ H.IsIndContained (PMVertex.graph m) ∧
          IsPurifiedRootedP4 (PMVertex.graph m)
            (PMVertex.B₁ m) (PMVertex.B₂ m) (PMVertex.B₃ m) (PMVertex.B₄ m) (PMVertex.Y m) ∧
          (PMVertex.middleEdges m).card = m ∧
          (crossingTraceFamily (PMVertex.graph m)
            (PMVertex.B₁ m) (PMVertex.B₂ m) (PMVertex.B₃ m) (PMVertex.B₄ m)
            (PMVertex.Y m)).Shatters (PMVertex.middleEdges m)) ∧
      (¬ BooleanStarCubeClosure H →
        ∀ m : ℕ,
          ¬ H.IsIndContained (BSVertex.graph m) ∧
            IsPurifiedRootedP4 (BSVertex.graph m)
              (BSVertex.B₁ m) (BSVertex.B₂ m) (BSVertex.B₃ m) (BSVertex.B₄ m) (BSVertex.Y m) ∧
            (BSVertex.middleEdges m).card = m ∧
            (crossingTraceFamily (BSVertex.graph m)
              (BSVertex.B₁ m) (BSVertex.B₂ m) (BSVertex.B₃ m) (BSVertex.B₄ m)
              (BSVertex.Y m)).Shatters (BSVertex.middleEdges m)) := by
  exact ⟨fun hH m => H_specific_privateMatching_cubes hH m,
    fun hH m => H_specific_booleanStar_cubes hH m⟩

end Erdos61
