import FormalConjectures.Problems.Erdos.E20.Kernels.SeparatorLifting
import FormalConjectures.Problems.Erdos.E20.Kernels.UniversalRouting

set_option linter.style.longLine false

namespace FormalConjectures.Problems.Erdos.E20

/-!
# Neutral Exact-Interface Confluence

This file records the abstract interface layer suggested by the pasted neutral
exact-interface note.

We do not model the transport groupoid itself here.  Instead, we package the
only logical consequence used downstream: a neutral interface dichotomy that
returns either compatibility or a profitable prefix block already gives the
same solved-or-profitable conclusion as the routing reduction.
-/

variable {Kernel : Type*}

/-- The neutral exact-interface confluence interface: every large kernel is
either compatible or already carries a profitable prefix block. -/
def NeutralExactInterfaceConfluence
    {IsLarge IsCompatible HasProfitablePrefixBlock : Kernel → Prop} : Prop :=
  ∀ K, IsLarge K → IsCompatible K ∨ HasProfitablePrefixBlock K

/-- Visible split forcing gives the neutral exact-interface confluence interface. -/
theorem visibleSplitForcing_implies_neutralExactInterfaceConfluence
    {IsLarge IsCompatible HasProfitablePrefixBlock : Kernel → Prop}
    (hVS : ∀ K, IsLarge K → HasProfitablePrefixBlock K) :
    NeutralExactInterfaceConfluence (Kernel := Kernel)
      (IsLarge := IsLarge) (IsCompatible := IsCompatible)
      (HasProfitablePrefixBlock := HasProfitablePrefixBlock) := by
  intro K hK
  exact Or.inr (hVS K hK)

/-- The neutral exact-interface interface feeds directly into universal routing. -/
theorem universalRouting_of_neutralExactInterfaceConfluence
    {IsLarge IsCompatible IsSolved HasProfitablePrefixBlock : Kernel → Prop}
    (hCR : ∀ K, IsCompatible K → IsSolved K)
    (hNE : NeutralExactInterfaceConfluence (Kernel := Kernel)
      (IsLarge := IsLarge) (IsCompatible := IsCompatible)
      (HasProfitablePrefixBlock := HasProfitablePrefixBlock)) :
    ∀ K, IsLarge K → IsSolved K ∨ HasProfitablePrefixBlock K := by
  exact universalRouting_of_compatibilityToRigidity_and_separatorCompatibleLifting
    (Kernel := Kernel) (IsLarge := IsLarge) (IsCompatible := IsCompatible)
    (IsSolved := IsSolved) (HasProfitablePrefixBlock := HasProfitablePrefixBlock)
    hCR hNE

section RankedLocalizability

variable {Support Loop : Type*}

/-- A ranked localizability interface for the neutral exact-interface notes.

The structure records only the logical data used by the pasted argument:

* residual loops on each support piece;
* bounded diamonds;
* proper subpieces;
* a rank function that strictly decreases along proper subpieces;
* a lift that transports a bounded diamond from a proper subpiece back to the ambient support;
* a one-step localization lemma.

Nothing here asserts that such data exists unconditionally.  It is a package for
the conditional theorem that follows. -/
structure NeutralExactInterfaceLocalizability (Support Loop : Type*) where
  ResidualLoop : Support → Loop → Prop
  BoundedDiamond : Support → Loop → Prop
  ProperSubpiece : Support → Support → Prop
  supportRank : Support → ℕ
  properSubpiece_lt :
    ∀ {T S}, ProperSubpiece T S → supportRank T < supportRank S
  liftBoundedDiamond :
    ∀ {T S γ}, ProperSubpiece T S → BoundedDiamond T γ → BoundedDiamond S γ
  localizes :
    ∀ {S γ}, ResidualLoop S γ →
      BoundedDiamond S γ ∨ ∃ T, ProperSubpiece T S ∧ ResidualLoop T γ

namespace NeutralExactInterfaceLocalizability

variable {Support Loop : Type*}
variable (L : NeutralExactInterfaceLocalizability Support Loop)

/-- The closure generated by bounded diamonds and proper-subpiece descent. -/
inductive GeneratedByBoundedDiamonds : Support → Loop → Prop
  | bounded {S γ} : L.BoundedDiamond S γ → GeneratedByBoundedDiamonds S γ
  | descend {S T γ} :
      L.ProperSubpiece T S → GeneratedByBoundedDiamonds T γ → GeneratedByBoundedDiamonds S γ

/-- Every residual loop is in the closure generated by bounded diamonds and proper subpieces. -/
theorem residualLoop_generatedByBoundedDiamonds :
    ∀ {S γ}, L.ResidualLoop S γ → L.GeneratedByBoundedDiamonds S γ := by
  have hwf : WellFounded (fun T S : Support => L.supportRank T < L.supportRank S) :=
    InvImage.wf L.supportRank Nat.lt_wfRel.wf
  let P : Support → Prop := fun S => ∀ {γ : Loop}, L.ResidualLoop S γ → L.GeneratedByBoundedDiamonds S γ
  have hstep : ∀ S, (∀ T, L.supportRank T < L.supportRank S → P T) → P S := by
    intro S ih γ hγ
    rcases L.localizes hγ with hbd | ⟨T, hTS, hT⟩
    · exact GeneratedByBoundedDiamonds.bounded (L := L) hbd
    · have hlt : L.supportRank T < L.supportRank S := L.properSubpiece_lt hTS
      exact GeneratedByBoundedDiamonds.descend (L := L) hTS (ih T hlt hT)
  have hP : ∀ S, P S := by
    intro S
    exact hwf.induction (C := P) S hstep
  intro S γ hγ
  simpa [P] using hP S hγ

/-- The ranked localizability package eliminates residual loops by induction on rank. -/
theorem boundedDiamond_of_residualLoop :
    ∀ {S γ}, L.ResidualLoop S γ → L.BoundedDiamond S γ := by
  have hwf : WellFounded (fun T S : Support => L.supportRank T < L.supportRank S) :=
    InvImage.wf L.supportRank Nat.lt_wfRel.wf
  let P : Support → Prop := fun S => ∀ {γ : Loop}, L.ResidualLoop S γ → L.BoundedDiamond S γ
  have hstep : ∀ S, (∀ T, L.supportRank T < L.supportRank S → P T) → P S := by
    intro S ih γ hγ
    rcases L.localizes hγ with hbd | ⟨T, hTS, hT⟩
    · exact hbd
    · have hlt : L.supportRank T < L.supportRank S := L.properSubpiece_lt hTS
      exact L.liftBoundedDiamond hTS (ih T hlt hT)
  have hP : ∀ S, P S := by
    intro S
    exact hwf.induction (C := P) S hstep
  intro S γ hγ
  simpa [P] using hP S hγ

end NeutralExactInterfaceLocalizability

end RankedLocalizability

end FormalConjectures.Problems.Erdos.E20
