import FormalConjectures.Problems.Erdos.E885.Findings.Defs
import FormalConjectures.Problems.Erdos.E885.Findings.SquareDiscriminant
import FormalConjectures.Problems.Erdos.E885.Findings.PairFiber
import FormalConjectures.Problems.Erdos.E885.Findings.Computations
import FormalConjectures.Problems.Erdos.E885.Findings.BSet
import FormalConjectures.Problems.Erdos.E885.Findings.ColumnLaw
import FormalConjectures.Problems.Erdos.E885.Findings.RowComplex
import FormalConjectures.Problems.Erdos.E885.Findings.Spectrum
import FormalConjectures.Problems.Erdos.E885.Findings.SquareTranslate
