import FormalConjectures.Problems.Erdos.E20.Defs
import FormalConjectures.Problems.Erdos.E20.Decomposition
import FormalConjectures.Problems.Erdos.E20.SeedProfile
import FormalConjectures.Problems.Erdos.E20.Branching
import FormalConjectures.Problems.Erdos.E20.CoverCriteria
import FormalConjectures.Problems.Erdos.E20.Obstructions
import FormalConjectures.Problems.Erdos.E20.Examples
import FormalConjectures.Problems.Erdos.E20.Correlation
import FormalConjectures.Problems.Erdos.E20.BetaChain
import FormalConjectures.Problems.Erdos.E20.GapAnalysis
import FormalConjectures.Problems.Erdos.E20.Counterexample
import FormalConjectures.Problems.Erdos.E20.TransversalCounterexample
import FormalConjectures.Problems.Erdos.E20.LeafStripping
import FormalConjectures.Problems.Erdos.E20.KernelBounds
import FormalConjectures.Problems.Erdos.E20.ExplicitKernels
import FormalConjectures.Problems.Erdos.E20.TerminalLinks
import FormalConjectures.Problems.Erdos.E20.ProjectionTransfer
import FormalConjectures.Problems.Erdos.E20.TupleStates
import FormalConjectures.Problems.Erdos.E20.RecurrenceReduction
import FormalConjectures.Problems.Erdos.E20.ProfitablePrefix
import FormalConjectures.Problems.Erdos.E20.FiniteStatePrefixes
import FormalConjectures.Problems.Erdos.E20.AutomatonBranches
import FormalConjectures.Problems.Erdos.E20.HereditaryGrowth
import FormalConjectures.Problems.Erdos.E20.FixedMemoryBound
import FormalConjectures.Problems.Erdos.E20.BranchBridgeCounterexample
import FormalConjectures.Problems.Erdos.E20.CharacterTensors
import FormalConjectures.Problems.Erdos.E20.QuinaryTensor
import FormalConjectures.Problems.Erdos.E20.InformalMap
