import FormalConjectures.Problems.Erdos.E20.Recurrences.ProjectionTransfer
import FormalConjectures.Problems.Erdos.E20.Recurrences.TupleStates
import FormalConjectures.Problems.Erdos.E20.Recurrences.RecurrenceReduction
import FormalConjectures.Problems.Erdos.E20.Recurrences.ProfitablePrefix
import FormalConjectures.Problems.Erdos.E20.Recurrences.FiniteStatePrefixes
import FormalConjectures.Problems.Erdos.E20.Recurrences.AutomatonBranches
import FormalConjectures.Problems.Erdos.E20.Recurrences.HereditaryGrowth
import FormalConjectures.Problems.Erdos.E20.Recurrences.FixedMemoryBound
